source "http://rubygems.org"

gem "rake"
gem "rails"
gem "sqlite3"

gem "delayed_job"
gem "delayed_job_active_record"
gem "mimetype-fu", require: "mimetype_fu"
gem "minitest-rails"

group :test do
  gem "cucumber-rails", require: false
  gem "database_cleaner"
  gem "capybara"
  gem "rspec-rails"
  gem "minitest-matchers"
  gem "email_spec", path: "../../", require: "email_spec"
end
